namespace go thrift_protocol
namespace java net.seefan.table_kv
service TableKV{
    binary Get(1:binary key)
    void Set(1:binary key,2:binary value)
    bool Exists(1:binary key)
    void Delete(1:binary key)
    void BatchSet(1:list<binary> keys ,2:list<binary> values)
    binary QGet()
    void QSet(1:binary value)
    void BatchQSet(1:list<binary> value)
    void BatchQGet(1:i16 size)
}